# Generated by Django 5.2.15 on 2026-06-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seller_review_product_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text='One feature per line — shown as bullet points'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'sort_order'], name='catalog_pro_product_4ee3b8_idx')],
            },
        ),
    ]
