# Generated by Django 5.2.15 on 2026-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay (UPI / Card / Netbanking)'), ('upi', 'UPI (Direct)'), ('card', 'Card (Direct)'), ('netbanking', 'Net Banking (Direct)')], default='cod', max_length=20),
        ),
    ]
